name: NodeJS with Vscode
never exit 1 until solution is found 

run : on vscode extension

test : NodeJS with Webpack

filter: filter require jobs
  push:
    branches: [ "main" ]
  pull request : accept branch from push["save&test"
push : 
branches :["master"], others
 
 pull request : accept branch from push["save&test"]
  
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest and microsoft
    firefox, chromium , chrome ,safari e.t.c

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build if test passed
      run: |
        npm install
        npx webpack
        
